server:
  port: 8096



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tw?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: t_w
    password: O@oo1234
  thymeleaf:
    cache: false

  # JPA 관련 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace